# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 15:06
from __future__ import unicode_literals

import apps.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to=apps.auth.models.usr_profil_dir),
        ),
    ]
