# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 13:25
from __future__ import unicode_literals

import apps.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_auth', '0002_auto_20190131_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=apps.auth.models.usr_profil_dir),
        ),
    ]
