# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_auth', '0004_resetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
