# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 18:07
from __future__ import unicode_literals

import apps.auth.models
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_auth', '0005_auto_20190202_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(help_text='Email field, need to be unique, will be trated as username', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='User first name', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='User profile photo', upload_to=apps.auth.models.usr_profil_dir),
        ),
    ]
