# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 11:42
from __future__ import unicode_literals

import apps.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_auth', '0006_auto_20190206_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='user/profile/fallback.png', help_text='User profile photo', upload_to=apps.auth.models.usr_profil_dir),
        ),
    ]
