# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 14:23
from __future__ import unicode_literals

import uuid

import django.contrib.postgres.fields.citext
import django.db.models.deletion
import partial_index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_id', models.UUIDField(default=uuid.uuid4,
                                                editable=False, unique=True, verbose_name='company id')),
                ('name', django.contrib.postgres.fields.citext.CICharField(
                    max_length=100, unique=True)),
                ('address', django.contrib.postgres.fields.citext.CITextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='company/logo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.PositiveIntegerField(choices=[
                    (0, 'TWITTER'), (2, 'GOOGLE'), (1, 'FACEBOOK')])),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='links', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('designation', models.PositiveIntegerField(choices=[
                    (0, 'HR'), (1, 'CEO'), (2, 'CTO'), (3, 'SDE-1'), (4, 'SDE-2')])),
                ('join_on', models.DateTimeField()),
                ('inactive_on', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[
                    (1, 'ACTIVE'), (0, 'INVITED'), (2, 'INACTIVE')])),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='users', to='company.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=partial_index.PartialIndex(
                fields=['user', 'company'], name='company_use_user_id_ad6b21_partial', unique=True,
                where=partial_index.PQ(status__in=(0, 1))),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('company', 'name')]),
        ),
    ]
