# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190131_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_companies', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='designation',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usercompanies', to=settings.AUTH_USER_MODEL),
        ),
    ]
