# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190201_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='join_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='left_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
