# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 13:25
from __future__ import unicode_literals

import apps.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190201_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.company.models.company_logo_dir),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='join_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
