# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190201_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
