# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(help_text='company address', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, help_text='company city', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(help_text='company name', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, help_text='company state', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'UNVERIFIED'), (2, b'ACTIVE'), (3, b'INACTIVE')], default=1, help_text='company logo'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.PositiveIntegerField(choices=[(1, b'TWITTER'), (2, b'FACEBOOK'), (3, b'GOOGLE')], default=1, help_text='company link type'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='link url'),
        ),
    ]
