# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20190207_1919'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercompany',
            name='company_use_user_id_099c95_partial',
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'UNVERIFIED'), (2, b'ACTIVE'), (3, b'INACTIVE')], default=1, help_text='company status'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=partial_index.PartialIndex(fields=['user', 'company'], name='company_use_user_id_a07d1a_partial', unique=True, where=partial_index.PQ(status=3)),
        ),
    ]
