# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 10:13
from __future__ import unicode_literals

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20190208_0930'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercompany',
            name='company_use_user_id_a07d1a_partial',
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=partial_index.PartialIndex(fields=['user', 'company'], name='company_use_user_id_9b3056_partial', unique=True, where=partial_index.PQ(status=2)),
        ),
    ]
