# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 12:50
from __future__ import unicode_literals

import apps.company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20190208_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to=apps.company.models.company_invite_csv_dir)),
                ('status', models.PositiveIntegerField(choices=[(1, b'PENDING'), (2, b'INPROGRESS'), (3, b'PROCESSED'), (4, b'ERROR')], default=1)),
                ('user_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvs', to='company.UserCompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
