# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 15:04
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0012_usercompanycsv'),
        ('workflow_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django.contrib.postgres.fields.citext.CICharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(null=True)),
                ('start_delta', models.DurationField(default=datetime.timedelta(0), help_text='time delay between completion of parent task and star of current task')),
                ('status', models.PositiveIntegerField(choices=[(1, b'UPCOMMING'), (2, b'ONGOING'), (3, b'COMPLETE')], default=1)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='company.UserCompany')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='workflow.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=256)),
                ('start_at', models.DateTimeField()),
                ('complete_at', models.DateTimeField(help_text='time when workflow completed', null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0), help_text='expected completion duration')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.UserCompany')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow_template.WorkflowTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.PositiveIntegerField(choices=[(1, b'READ'), (2, b'READ_WRITE')], default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.UserCompany')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowaccess',
            unique_together=set([('employee', 'workflow')]),
        ),
    ]
