# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190218_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='expected duration of the task'),
        ),
        migrations.AlterField(
            model_name='workflowaccess',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_workflows', to='company.UserCompany'),
        ),
        migrations.AlterField(
            model_name='workflowaccess',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessors', to='workflow.Workflow'),
        ),
    ]
