# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 15:06
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190131_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assigne',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='expected_end_time',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='workflow_id',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_delta',
            field=models.DurationField(default=datetime.timedelta(
                0), help_text='time delay between                                            completion of parent task and star of current task'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='completed_at',
            field=models.DateTimeField(
                help_text='time when workflow completed', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(
                0), help_text='expected completion duration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='workflow.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(
                choices=[(1, b'UPCOMMING'), (2, b'ONGOING'), (3, b'COMPLETE')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=256),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=256),
        ),
        migrations.AlterField(
            model_name='workflowaccess',
            name='permission',
            field=models.PositiveIntegerField(
                choices=[(1, b'READ'), (2, b'READ_WRITE')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='task',
            name='child_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='delta_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
