# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190218_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='workflow.Task'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='complete_at',
            field=models.DateTimeField(blank=True, help_text='time when workflow completed', null=True),
        ),
        migrations.AlterField(
            model_name='workflowaccess',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_workflows', to='company.UserCompany'),
        ),
        migrations.AlterField(
            model_name='workflowaccess',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessors', to='workflow.Workflow'),
        ),
    ]
