# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190222_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='duration',
        ),
    ]
