# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_workflow_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(help_text='expected duration of the task'),
        ),
    ]
