# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_merge_20190224_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='complete_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'INITIATED'), (2, b'INPROGRESS'), (3, b'COMPLETE')], default=1),
        ),
    ]
