# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20190225_1233'),
        ('workflow', '0008_merge_20190224_1208'),
    ]

    operations = [
    ]
