# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_merge_20190227_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'UPCOMING'), (2, b'SCHEDULED'), (3, b'ONGOING'), (4, b'COMPLETE')], default=1),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'INITIATED'), (2, b'SCHEDULED'), (3, b'INPROGRESS'), (4, b'COMPLETE')], default=1),
        ),
    ]
