# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20190228_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
