# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 15:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='template_id',
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=100, unique=True),
        ),
    ]
