# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 14:25
from __future__ import unicode_literals

import apps.workflow_template.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0002_auto_20190131_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Template thumbnail picture', upload_to=apps.workflow_template.models.thumbnail_dir),
        ),
    ]
