# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0003_workflowtemplate_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowtemplate',
            old_name='template',
            new_name='structure',
        ),
    ]
