from collections import namedtuple

_DESIGNATION = namedtuple('DESIGNATION', 'HR CEO CTO SDE_1 SDE_2')
_USER_STATUS = namedtuple('STATUS', 'INVITED ACTIVE INACTIVE')
_LINK_TYPE = namedtuple('LINK_TYPE', 'TWITTER FACEBOOK GOOGLE')
_TASK_STATUS = namedtuple('TASK_STATUS', 'UPCOMMING ONGOING COMPLETE')
_PERMISSION = namedtuple('PERMISSION', 'READ READ_WRITE')
_COMPANY_STATUS = namedtuple('COMPANY_STATUS', 'UNVERIFIED ACTIVE INACTIVE')

DESIGNATION = _DESIGNATION._make(xrange(1, 6))
USER_STATUS = _USER_STATUS._make(xrange(1, 4))
LINK_TYPE = _LINK_TYPE._make(xrange(1, 4))
TASK_STATUS = _TASK_STATUS._make(xrange(1, 4))

PERMISSION = _PERMISSION._make(xrange(1, 3))
COMPANY_STATUS = _COMPANY_STATUS._make(xrange(1, 4))
