# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.PositiveIntegerField(choices=[(1, b'CREATE'), (2, b'UPDATE'), (3, b'DELETE')], default=1, help_text='history action'),
            preserve_default=False,
        ),
    ]
